Do remove broken symlinks

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,4 +1,23 @@
 #!/usr/bin/env bash
 echo "-----> Fixing the broken heroku-datadog-buildpack"
 
+# Fail fast
+set -e
+set -o pipefail
+
+# Parse and derive params
+BUILD_DIR=$1
+CACHE_DIR=$2
+ENV_DIR=$3
+BUILDPACK_DIR=$(cd "$(dirname "$0")"; cd ..; pwd)
+
+# Setup apt environment
+APT_DIR="$BUILD_DIR/.apt"
+
+BROKEN_SYMLINKS=(postmaster)
+
+for i in "${BROKEN_SYMLINKS[@]}"; do
+  rm -rf "$APT_DIR"/opt/datadog-agent/embedded/bin/"$i"
+done
+
 exit 0
